### ISSUE TITLE
Provide a licence and a release tarball

### ISSUE THREAD

**Issue by wigust** [cute-jumper/epipe#2]
Hello Junpeng,

Thank you for this program!

Could I ask you about including a LICENCE file in this Git repository?  Maybe a GPL3+ would serve well for this, because most of Emacs related stuff is under GPL3+ licence.  WDYT?  Also a release tarball would be great.  I want to publish this program to Guix[1] package collection.

[1] https://www.gnu.org/software/guix/

Oleg.

**Comment by cute-jumper** [comment]
Sorry for the late reply! Been very busy recently. I've added GPL v3 in the newest commit. As for the tarball, I'm not familiar with Guix. What files should be included?

Thanks for the interest!

**Comment by wigust** [comment]
> Sorry for the late reply! Been very busy recently.

No problem!

> I've added GPL v3 in the newest commit.

Thank you!

> As for the tarball.

Just add a tag, for example: v0.0.1.  Then make a `git push --tags`.

> I'm not familiar with Guix.  What files should be included?

No requirements, except a free license and if possible a tarball.

Oleg.

**Comment by cute-jumper** [comment]
Tag 0.1.0 has been pushed and the release tarball seems to be created, too. Let me know if there is any issue. Thanks!

**Comment by wigust** [comment]
> Tag 0.1.0 has been pushed and the release tarball seems to be created, too.

Yes, it's created.  Thank you!

I'll close the issue.
